# Generated by Django 3.1.3 on 2021-01-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210117_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
